In [1]:
import numpy as np

In [2]:
# X = idades
# Y = salarios

x = [21, 23, 27, 32, 34, 41, 50, 53, 57, 59, 38, 46, 48, 48, 60]
y = [1000, 1100, 1250, 1700, 1500, 1980, 2500, 3500, 2200, 4100, 3900, 5100, 5500, 7000, 6500]

In [3]:
import plotly.express as px

In [4]:
grafico = px.scatter(x=x, y=y) # verificar porque esta com erro ao usar o plotly.express
grafico.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [ ]:
base_salario = np.array([[21,1000],[23,1100], [27,1250], [32, 1700],
                        [34,1500],[41,1980],[38,3900],[46,5100],
                        [46,5500],[48,7000],[53,3500],[57,2200],[59,4100],
                        [60,6500],[50,2500]])

In [ ]:
base_salario

array([[  21, 1000],
       [  23, 1100],
       [  27, 1250],
       [  32, 1700],
       [  34, 1500],
       [  41, 1980],
       [  38, 3900],
       [  46, 5100],
       [  46, 5500],
       [  48, 7000],
       [  53, 3500],
       [  57, 2200],
       [  59, 4100],
       [  60, 6500],
       [  50, 2500]])

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)

In [ ]:
base_salario

array([[-1.72382169, -1.15955852],
       [-1.56221341, -1.10814445],
       [-1.23899684, -1.03102336],
       [-0.83497613, -0.79966007],
       [-0.67336785, -0.9024882 ],
       [-0.10773886, -0.65570069],
       [-0.35015128,  0.33144933],
       [ 0.29628185,  0.9484181 ],
       [ 0.29628185,  1.15407435],
       [ 0.45789014,  1.92528531],
       [ 0.86191085,  0.12579308],
       [ 1.18512741, -0.54258975],
       [ 1.3467357 ,  0.43427746],
       [ 1.42753984,  1.66821499],
       [ 0.61949842, -0.38834756]])

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

c:\Users\GAMERX\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



KMeans(n_clusters=3)

In [ ]:
centroide = kmeans_salario.cluster_centers_
centroide

array([[ 0.59256371, -0.11585302],
       [ 0.61949842,  1.42399818],
       [-1.20667519, -1.00017492]])

In [ ]:
scaler_salario.inverse_transform(kmeans_salario.cluster_centers_)

array([[  49.66666667, 3030.        ],
       [  50.        , 6025.        ],
       [  27.4       , 1310.        ]])

In [ ]:
rotulos = kmeans_salario.labels_
rotulos

array([2, 2, 2, 2, 2, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0])

In [ ]:
import plotly.graph_objects as go
grafico1 = px.scatter(x = base_salario[:,0], y =base_salario[:,1], color = rotulos)
grafico2 = px.scatter(x = centroide[:,0], y=centroide[:,1], size = [8,8,8])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico3.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed