In [2]:
import numpy as np

# array 1D
l = [1, 2, 3]
x = np.array(l)
print(f'x = {x}')
print('shape:', x.shape)


x = [1 2 3]
shape: (3,)


In [3]:
# array 2D

l = [[1, 2], [3, 4]]
x = np.array(l)
print('x:\n', x)
print('shape', x.shape)


x:
 [[1 2]
 [3 4]]
shape (2, 2)


In [10]:
# array apenas com zeros

dim = (2, 2)

x = np.zeros(dim)
print('x:\n', x)
print('shape', x.shape)

x:
 [[0. 0.]
 [0. 0.]]
shape (2, 2)


In [11]:
# array apenas com 1

size = (2, 2)
x = np.ones(size)
print('x:\n', x)
print('shape', x.shape)

x:
 [[1. 1.]
 [1. 1.]]
shape (2, 2)


In [16]:
# criação de valores dentro de um intervalo
# valores uniformes entre intervalos

x_min, x_max = 5, 15
x = np.linspace(start=x_min, stop=x_max, num=6)
print('x:', x)
print('shape', x.shape)

x: [ 5.  7.  9. 11. 13. 15.]
shape (6,)


In [18]:
# criação de matriz identidade
n = 4
x = np.eye(n)
print('x:', x)
print('shape', x.shape)

x: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
shape (4, 4)


In [19]:
# criação de valores aleatorios

x = np.random.random(size=(2, 3))
print('x:\n', x)
print('shape', x.shape)

x:
 [[0.75710844 0.27349845 0.83419937]
 [0.60432261 0.40356501 0.11122679]]
shape (2, 3)
