In [1]:
import numpy as np

In [4]:
x = np.linspace(start=10, stop=100, num=10)

print('x:', x)
print('shape:', x.shape)

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
shape: (10,)


In [6]:
# extração de elementos 
print('x:', x)
print(x[0])

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
10.0


In [7]:
# extração de subarrays
print('x:', x)
print(x[:2])

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[10. 20.]


In [8]:
# arrays 2D

x = x.reshape(2, 5)
print('x:\n', x)

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [12]:
# extração de subarrays

print(x[0, :5]) # primeira linha
print(x[0, 1:4]) # primeira linha 2 a 4 coluna
print(x[:, [-1]]) # ultima coluna, coluca entre colchete para manter o formato de coluna

[10. 20. 30. 40. 50.]
[20. 30. 40.]
[[ 50.]
 [100.]]


# atenção



In [14]:
x =np.array([1, 2, 3])
print('x antes:'), x
y = x[:2]
y[0] = -100
print('x depois:', x)

x antes:
x depois: [-100    2    3]


In [15]:
# usar copy

x =np.array([1, 2, 3])
print('x antes:'), x
y = x[:2].copy()
y[0] = -100
print('x depois:', x)

x antes:
x depois: [1 2 3]


## Indexação boleana

In [18]:
a = np.array([1, 2, 3])

cond = a <= 2
d = a[cond]

print(cond)
print(d) # retorna os valores onde a condição é verdadeira

[ True  True False]
[1 2]
