In [1]:
import numpy as np


In [3]:
x = np.array([[1, 3, 7],
             [4, 11, 2],
             [42, 8, 9]])

print(x)


[[ 1  3  7]
 [ 4 11  2]
 [42  8  9]]


In [4]:
# reshape: transforma a matriz em um vetor coluna
print(x.reshape(9, 1))


[[ 1]
 [ 3]
 [ 7]
 [ 4]
 [11]
 [ 2]
 [42]
 [ 8]
 [ 9]]


In [5]:
# Transposição de matriz
print(x.T)


[[ 1  4 42]
 [ 3 11  8]
 [ 7  2  9]]


In [7]:
# soma de todos os elementos
print(x)
print(np.sum(x))


[[ 1  3  7]
 [ 4 11  2]
 [42  8  9]]
87


In [8]:
# soma dos elementos nas linhas axix = 0
print(x)
print(np.sum(x, axis=0))


[[ 1  3  7]
 [ 4 11  2]
 [42  8  9]]
[47 22 18]


In [9]:
# soma dos elementos nas colunas axix = 1
print(x)
print(np.sum(x, axis=1))


[[ 1  3  7]
 [ 4 11  2]
 [42  8  9]]
[11 17 59]


In [11]:
# media ao longo das linhas e colunas

print(x)
print(np.mean(x))
print(np.mean(x, axis=0))
print(np.mean(x, axis=1))


[[ 1  3  7]
 [ 4 11  2]
 [42  8  9]]
9.666666666666666
[15.66666667  7.33333333  6.        ]
[ 3.66666667  5.66666667 19.66666667]


In [15]:
cond = x % 2 == 0
print(x)
print(cond)
i, j = np.where(cond)
print('indice i (linhas)', i)
print('indice j (linhas)', j)


[[ 1  3  7]
 [ 4 11  2]
 [42  8  9]]
[[False False False]
 [ True False  True]
 [ True  True False]]
indice i (linhas) [1 1 2 2]
indice j (linhas) [0 2 0 1]
